### ISSUE TITLE
iOS beta page signup is broken

### ISSUE THREAD

**Issue by einsteinx2** [balancemymoney/balance-open#300]
I'm seeing the same as well

![uploads/8e8c9345-972c-4d7d-8e27-0db7cd7aa2a2/Image uploaded from iOS.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8e8c9345-972c-4d7d-8e27-0db7cd7aa2a2%2FImage+uploaded+from+iOS.png)

And here are the logs of me trying a test:
```
2017-11-20T20:58:14.100764+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
2017-11-20T20:58:14.100767+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
2017-11-20T20:58:14.100768+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application.rb:165:in `call'
2017-11-20T20:58:14.100768+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:518:in `call'
2017-11-20T20:58:14.100769+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
2017-11-20T20:58:14.100772+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2017-11-20T20:58:14.100770+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
2017-11-20T20:58:14.100770+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
2017-11-20T20:58:14.100771+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
2017-11-20T20:58:14.104980+00:00 app[web.1]: Completed 200 OK in 1417ms (Views: 3.8ms)
2017-11-20T20:58:14.102136+00:00 app[web.1]:   Rendered invite/index.html.erb within layouts/application (0.3ms)
2017-11-20T21:00:07.796064+00:00 app[web.1]: Started POST "/submit" for 186.86.31.46 at 2017-11-20 21:00:07 +0000
2017-11-20T21:00:07.798312+00:00 app[web.1]: Processing by InviteController#submit as HTML
2017-11-20T21:00:07.798406+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"B20Md8U2Y9Bx0lJIp23VXhvAorpga+iJa8+ZbwklwWU6Au0CorZUUVH2PGnNlwVYY9jAVaw2l1c4ur+rU3N8WA==", "first_name"=>"Test", "last_name"=>"Test2", "email"=>"test@test.com"}
2017-11-20T21:00:07.799315+00:00 app[web.1]: Creating a new tester: test@test.com - Test Test2
2017-11-20T21:00:09.496184+00:00 app[web.1]: #<Spaceship::Client::UnexpectedResponse: <?xml version="1.0" encoding="UTF-8"?>
2017-11-20T21:00:09.496196+00:00 app[web.1]: <String>There is no route for the path 'user/internalTesters/1300292386/'.</String>
2017-11-20T21:00:09.496197+00:00 app[web.1]: >
2017-11-20T21:00:09.514737+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/client.rb:588:in `parse_response'
2017-11-20T21:00:09.514742+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/tunes/tunes_client.rb:1094:in `testers_by_app'
2017-11-20T21:00:09.514742+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/tunes/tester.rb:121:in `all_by_app'
2017-11-20T21:00:09.514743+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/fastlane-2.53.1/spaceship/lib/spaceship/tunes/tester.rb:129:in `find_by_app'
2017-11-20T21:00:09.514744+00:00 app[web.1]: /app/app/services/boarding_service.rb:120:in `find_app_tester'
2017-11-20T21:00:09.514745+00:00 app[web.1]: /app/app/services/boarding_service.rb:44:in `add_tester'
2017-11-20T21:00:09.514746+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:92:in `create_and_add_tester'
2017-11-20T21:00:09.514747+00:00 app[web.1]: /app/app/controllers/invite_controller.rb:75:in `submit'
2017-11-20T21:00:09.514747+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
2017-11-20T21:00:09.514748+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/base.rb:198:in `process_action'
2017-11-20T21:00:09.514749+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rendering.rb:10:in `process_action'
2017-11-20T21:00:09.514749+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
2017-11-20T21:00:09.514750+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:117:in `call'
2017-11-20T21:00:09.514751+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
2017-11-20T21:00:09.514752+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'
2017-11-20T21:00:09.514752+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
2017-11-20T21:00:09.514753+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
2017-11-20T21:00:09.514754+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
2017-11-20T21:00:09.514755+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/callbacks.rb:19:in `process_action'
2017-11-20T21:00:09.514755+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rescue.rb:29:in `process_action'
2017-11-20T21:00:09.514757+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
2017-11-20T21:00:09.514757+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `block in instrument'
2017-11-20T21:00:09.514758+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2017-11-20T21:00:09.514759+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `instrument'
2017-11-20T21:00:09.514760+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
2017-11-20T21:00:09.514760+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
2017-11-20T21:00:09.514761+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/base.rb:137:in `process'
2017-11-20T21:00:09.514775+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/rendering.rb:30:in `process'
2017-11-20T21:00:09.514776+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal.rb:196:in `dispatch'
2017-11-20T21:00:09.514777+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
2017-11-20T21:00:09.514778+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal.rb:237:in `block in action'
2017-11-20T21:00:09.514779+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
2017-11-20T21:00:09.514779+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:43:in `serve'
2017-11-20T21:00:09.514780+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:43:in `block in serve'
2017-11-20T21:00:09.514781+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:30:in `each'
2017-11-20T21:00:09.514781+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:30:in `serve'
2017-11-20T21:00:09.514782+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:817:in `call'
2017-11-20T21:00:09.514783+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/http_accept_language-2.0.5/lib/http_accept_language/middleware.rb:14:in `call'
2017-11-20T21:00:09.514819+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
2017-11-20T21:00:09.514820+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/conditionalget.rb:38:in `call'
2017-11-20T21:00:09.514821+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
2017-11-20T21:00:09.514822+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
2017-11-20T21:00:09.514823+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/flash.rb:260:in `call'
2017-11-20T21:00:09.514823+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
2017-11-20T21:00:09.514824+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
2017-11-20T21:00:09.514825+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/cookies.rb:560:in `call'
2017-11-20T21:00:09.514825+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
2017-11-20T21:00:09.520600+00:00 heroku[router]: at=info method=POST path="/submit" host=balance-ios-testflight.herokuapp.com request_id=c3b20fbb-a2e8-41c6-bcae-69f0444d3dbd fwd="186.86.31.46" dyno=web.1 connect=0ms service=1726ms status=200 bytes=2492 protocol=https
2017-11-20T21:00:09.514826+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
2017-11-20T21:00:09.514835+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
2017-11-20T21:00:09.514836+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
2017-11-20T21:00:09.514837+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2017-11-20T21:00:09.514838+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2017-11-20T21:00:09.514838+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2017-11-20T21:00:09.514839+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2017-11-20T21:00:09.514840+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:38:in `call_app'
2017-11-20T21:00:09.514840+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:20:in `block in call'
2017-11-20T21:00:09.514841+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2017-11-20T21:00:09.514842+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:26:in `tagged'
2017-11-20T21:00:09.514843+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:68:in `tagged'
2017-11-20T21:00:09.514843+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:20:in `call'
2017-11-20T21:00:09.514844+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2017-11-20T21:00:09.514845+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
2017-11-20T21:00:09.514845+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
2017-11-20T21:00:09.514846+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2017-11-20T21:00:09.514847+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/static.rb:120:in `call'
2017-11-20T21:00:09.514848+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
2017-11-20T21:00:09.514848+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:518:in `call'
2017-11-20T21:00:09.514849+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application.rb:165:in `call'
2017-11-20T21:00:09.514850+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
2017-11-20T21:00:09.514850+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
2017-11-20T21:00:09.514851+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
2017-11-20T21:00:09.514852+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
2017-11-20T21:00:09.514852+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
2017-11-20T21:00:09.517307+00:00 app[web.1]:   Rendered invite/index.html.erb within layouts/application (0.2ms)
2017-11-20T21:00:09.519035+00:00 app[web.1]: Completed 200 OK in 1720ms (Views: 3.7ms)
```

**Comment by reddavis** [comment]
Itunes connect changed recently causing Fastlane tools to break: https://github.com/fastlane/boarding/issues/186

I've updated to the latest version, it does still show an error but the user is added as a tester and receives the email.

I'm watching the issue and will update the boarding app when the last error gets fixed

**Comment by reddavis** [comment]
@einsteinx2 has now updated fastlane to the latest commit
